[versions]
kotlin = "2.2.21"
android-gradle-plugin = "8.13.2"
ktfmt = "0.25.0"
intellij-platform = "2.10.5"
changelog = "2.5.0"
foojay-resolver = "0.9.0"
gradle-plugin-publish = "1.3.1"
junit4 = "4.13.2"
junit5 = "5.11.4"
truth = "1.4.5"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
android-lint = { id = "com.android.lint", version.ref = "android-gradle-plugin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-platform" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
foojay-resolver = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay-resolver" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-plugin-publish" }
